"""答案生成：重排 top-6 的父文档 + 题型化提示词 -> 结构化 CoT 答案（第 8 步）。

对应原项目 prompts.py 的 AnswerWithRAGContext*Prompt 系列 + api_requests.py 的
get_answer_from_rag_context。忠实保留的部分（2026-09-08 讨论）：
- 共享 instruction：只依据上下文作答；题目是模板生成的，可能有陷阱（相似值
  不是所求值）
- 上下文格式：`Text retrieved from page {N}:` + 引号块 + `---` 连接——
  relevant_pages 的页号锚点全靠它
- 四种题型 schema（题目 json 的 kind 字段路由）：
  name（单名，原样摘取）/ names（名单）/ number（严格度量匹配：单位
  thousands/millions 换算、括号=负数、币种不符->N/A、拒绝计算推导）/ boolean
- CoT 字段：step_by_step_analysis（>=5 步 >=150 词）、reasoning_summary（~50 词）、
  relevant_pages（只列直接支撑答案的页）、final_answer
- relevant_pages 校验（原版 _validate_page_references）：只保留上下文里
  实际提供的页（防幻觉页码），不足 2 页用重排最高分的页补足、至多 8 页

我们的调整：
- 模型 deepseek-chat（json_object + pydantic 校验 + 3 次重试，同前几步模式）
- **弱证据提示注入**（原版没有）：第 7 步冒烟发现可答题 top 重排 LLM 分
  0.9-1.0、弱证据题 <=0.7——当 top 分 <= 阈值（默认 0.5）时在 system 追加
  "检索证据可能不足，认真考虑 N/A"，降低编造率

用法（冒烟，全链路 路由->检索->重排->父文档->生成）：
    python -m enterprise_rag.generation.generator "问题" \
        [--kind name|names|number|boolean|auto] [--weak-th 0.5] [--top-n 6]
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from enterprise_rag.reranking.reranker import Reranker, make_client
from enterprise_rag.retrieval.retriever import DATA_DIR, Router, Retriever, _snippet

# —— 共享 instruction：忠实原版 AnswerWithRAGContextSharedPrompt ——
INSTRUCTION = """You are a RAG (Retrieval-Augmented Generation) answering system.
Your task is to answer the given question based only on information from the company's annual report, which is uploaded in the format of relevant pages extracted using RAG.

Before giving a final answer, carefully think out loud and step by step. Pay special attention to the wording of the question.
- Keep in mind that the content containing the answer may be worded differently than the question.
- The question was autogenerated from a template, so it may be meaningless or not applicable to the given company.
"""

USER_PROMPT = """
Here is the context:
\"\"\"
{context}
\"\"\"

---

Here is the question:
"{question}"
"""

WEAK_EVIDENCE_NOTE = (
    "\nWarning: the retrieved evidence for this question appears weak "
    "(the best matching blocks were rated only marginally relevant). "
    "If the context does not contain the requested information, you MUST "
    "return 'N/A' rather than guessing.\n"
)

# —— 各题型 final_answer 规则（忠实原版 Field 描述）——
FINAL_ANSWER_RULES = {
    "name": """
If it is a company name, should be extracted exactly as it appears in question.
If it is a person name, it should be their full name.
If it is a product name, it should be extracted exactly as it appears in the context.
Without any extra information, words or comments.
- Return 'N/A' if information is not available in the context
""",
    "names": """
Each entry should be extracted exactly as it appears in the context.
Without any extra information, words or comments.
- Return 'N/A' if information is not available in the context
""",
    "number": """
An exact metric number is expected as the answer.
- Example for percentages:
    Value from context: 58,3%
    Final answer: 58.3

Pay special attention to any mentions in the context about whether metrics are reported in units, thousands, or millions to adjust number in final answer with no changes, three zeroes or six zeroes accordingly.
Pay attention if value wrapped in parentheses, it means that value is negative.

- Example for negative values:
    Value from context: (2,124,837) CHF
    Final answer: -2124837

- Example for numbers in thousands:
    Value from context: 4970,5 (in thousands $)
    Final answer: 4970500

- Return 'N/A' if metric provided is in a different currency than mentioned in the question
    Example of value from context: 780000 USD, but question mentions EUR
    Final answer: 'N/A'
""",
    "boolean": """
A boolean value (True or False) extracted from the context that precisely answers the question.
If question ask about did something happen, and in context there is information about it, return False.
""",
}

# number 题的 step_by_step_analysis 专用版（严格度量匹配，忠实原版）
COT_NUMBER = """
Detailed step-by-step analysis of the answer with at least 5 steps and at least 150 words.
**Strict Metric Matching Required:**

1. Determine the precise concept the question's metric represents. What is it actually measuring?
2. Examine potential metrics in the context. Don't just compare names; consider what the context metric measures.
3. Accept ONLY if: The context metric's meaning *exactly* matches the target metric. Synonyms are acceptable; conceptual differences are NOT.
4. Reject (and use 'N/A') if:
    - The context metric covers more or less than the question's metric.
    - The context metric is a related concept but not the *exact* equivalent (e.g., a proxy or a broader category).
    - Answering requires calculation, derivation, or inference.
    - Aggregation Mismatch: The question needs a single value but the context offers only an aggregated total
5. No Guesswork: If any doubt exists about the metric's equivalence, default to `N/A`.
"""

COT_DEFAULT = (
    "Detailed step-by-step analysis of the answer with at least 5 steps and at "
    "least 150 words. Pay special attention to the wording of the question to "
    "avoid being tricked. Sometimes it seems that there is an answer in the "
    "context, but this is might be not the requested value, but only a similar one.")

RELEVANT_PAGES_DESC = """
List of page numbers containing information directly used to answer the question. Include only:
- Pages with direct answers or explicit statements
- Pages with key information that strongly supports the answer
Do not include pages with only tangentially related information or weak connections to the answer.
At least one page should be included in the list.
"""


# —— 题型化 pydantic schema（json_object 模式下由 JSON_FORMAT 描述形状）——
class _Common(BaseModel):
    step_by_step_analysis: str
    reasoning_summary: str = Field(description="~50 words")
    relevant_pages: list[int]


class NameAnswer(_Common):
    final_answer: str


class NamesAnswer(_Common):
    final_answer: list[str] | str  # 'N/A' 或名单


class NumberAnswer(_Common):
    final_answer: float | str  # 'N/A' 或数值


class BooleanAnswer(_Common):
    # 原版只收 bool（题目模板要求无证据回 False）；但弱证据提示会引导模型
    # 回 'N/A'——schema 与提示必须自洽，否则重试 3 次全挂（round2 冒烟踩过）
    final_answer: bool | Literal["N/A"]


SCHEMAS: dict[str, type[BaseModel]] = {
    "name": NameAnswer, "names": NamesAnswer,
    "number": NumberAnswer, "boolean": BooleanAnswer,
}


def json_format_instruction(kind: str) -> str:
    """按题型生成输出形状说明（DeepSeek json 模式必须显式给形状）。"""
    fa = {
        "name": '"final_answer": "..."（按 final_answer 规则，可为 "N/A"）',
        "names": '"final_answer": ["...", ...]（名单，无答案则 "N/A"）',
        "number": '"final_answer": 58.3（数值，单位换算后；无答案则 "N/A"）',
        "boolean": '"final_answer": true 或 false',
    }[kind]
    return f"""
Return only valid json (no markdown fences) of exactly this shape:
{{
  "step_by_step_analysis": "...",
  "reasoning_summary": "...",
  "relevant_pages": [12, 34],
  {fa}
}}
"""


def guess_kind(question: str) -> str:
    """CLI 单题冒烟用的简易题型猜测（正式批量跑读题目 json 的 kind 字段）。"""
    q = question.strip().lower()
    if q.startswith(("did ", "does ", "is ", "was ", "were ", "has ", "have ")):
        return "boolean"
    if any(w in q for w in ("how many", "what was the value", "what is the value",
                            "(%)", "in usd", "amount")):
        return "number"
    if any(w in q for w in ("who were", "names of", "list of", "members of")):
        return "names"
    return "name"


class Generator:
    """父文档上下文 + 题型化提示词 -> 结构化答案。"""

    def __init__(self, client=None, model: str | None = None, retries: int = 3) -> None:
        if client is None or model is None:
            client, model = make_client()
        self.client = client
        self.model = model
        self.retries = retries
        self.tokens_in = 0
        self.tokens_out = 0

    def answer(self, question: str, context_pages: list[dict], kind: str = "name",
               weak_evidence: bool = False) -> dict:
        """context_pages: [{"page": int, "text": str}]（parent_context pages 模式输出）。"""
        if kind not in SCHEMAS:
            raise ValueError(f"未知题型 {kind}，可选: {list(SCHEMAS)}")
        context = "\n\n---\n\n".join(
            f'Text retrieved from page {p["page"]}: \n"""\n{p["text"]}\n"""'
            for p in context_pages)
        system = INSTRUCTION + json_format_instruction(kind) \
            + "\nfinal_answer rules:" + FINAL_ANSWER_RULES[kind]
        if kind == "number":
            system += "\nstep_by_step_analysis requirements:" + COT_NUMBER
        if weak_evidence:
            system += WEAK_EVIDENCE_NOTE

        last_err: Exception | None = None
        for attempt in range(self.retries):
            try:
                resp = self.client.chat.completions.create(
                    model=self.model, temperature=0, max_tokens=2048,
                    response_format={"type": "json_object"},
                    messages=[
                        {"role": "system", "content": system},
                        {"role": "user",
                         "content": USER_PROMPT.format(context=context, question=question)},
                    ], timeout=180)
                usage = resp.usage
                if usage:
                    self.tokens_in += usage.prompt_tokens
                    self.tokens_out += usage.completion_tokens
                parsed = SCHEMAS[kind].model_validate(
                    json.loads(resp.choices[0].message.content or ""))
                d = parsed.model_dump()
                d["relevant_pages"] = self._validate_pages(
                    d.get("relevant_pages", []), context_pages)
                return d
            except Exception as e:  # noqa: BLE001 —— JSON 越界/网络，走重试
                last_err = e
                time.sleep(2 * (attempt + 1))
        raise RuntimeError(f"答案生成失败（已重试 {self.retries} 次）: {last_err}")

    @staticmethod
    def _validate_pages(pages: list[int], context_pages: list[dict],
                        min_pages: int = 2, max_pages: int = 8) -> list[int]:
        """页码校验（同原版 _validate_page_references）：只留上下文真实提供的页，
        不足 min 用上下文首页补足（重排序即相关度序），超出 max 截断。"""
        provided = [p["page"] for p in context_pages]
        valid = [p for p in dict.fromkeys(pages) if p in provided]
        for p in provided:            # 不足则按上下文顺序补
            if len(valid) >= min_pages:
                break
            if p not in valid:
                valid.append(p)
        return valid[:max_pages]


def main() -> None:
    ap = argparse.ArgumentParser(
        description="第 8 步生成冒烟：全链路 路由->双路融合->重排->父文档->结构化答案")
    ap.add_argument("question")
    ap.add_argument("--kind", default="auto",
                    choices=["auto", "name", "names", "number", "boolean"])
    ap.add_argument("--top-n", type=int, default=6, help="重排输出（父文档来源）")
    ap.add_argument("--weak-th", type=float, default=0.5,
                    help="top 重排 LLM 分 <= 此值注入弱证据提示（0=关闭）")
    ap.add_argument("--max-context-chars", type=int, default=60000)
    args = ap.parse_args()
    kind = guess_kind(args.question) if args.kind == "auto" else args.kind

    router = Router(DATA_DIR / "pdf_metadata.csv", DATA_DIR / "parsed" / "chunked")
    doc_ids = router.route(args.question)
    if not doc_ids:
        print("路由失败：问题里没匹配到任何已索引文档的公司名/stem", flush=True)
        sys.exit(1)
    note = "（比较题多公司：当前取第一家演示，拆解与汇总属第 9 步端到端范围）" \
        if len(doc_ids) > 1 else ""
    print(f"路由 -> {doc_ids}{note}；题型 {kind}", flush=True)

    from enterprise_rag.indexing.ingestor import make_embedder
    retriever = Retriever(embedder=make_embedder())
    cands = retriever.retrieve(args.question, doc_ids[0], top_n=20)
    reranker = Reranker()
    top = reranker.rerank(args.question, cands, top_n=args.top_n)

    parents = retriever.parent_context(doc_ids[0], top)
    kept, total = [], 0
    for p in parents:                 # 上下文长度保险丝（超限丢弃靠后的段）
        if total + len(p["text"]) > args.max_context_chars:
            print(f"  [WARN] 上下文超 {args.max_context_chars} 字符，丢弃 p{p['page']}"
                  " 起的后续页", flush=True)
            break
        kept.append(p)
        total += len(p["text"])

    top_llm = max(c["relevance_score"] for c in top)
    weak = args.weak_th > 0 and top_llm <= args.weak_th
    print(f"重排 top1 LLM 分 {top_llm:.1f}"
          f"{' -> 注入弱证据提示' if weak else ''}；父文档 "
          f"{len(kept)} 页 {total} 字符: {' '.join('p' + str(p['page']) for p in kept)}",
          flush=True)

    gen = Generator()
    ans = gen.answer(args.question, kept, kind=kind, weak_evidence=weak)

    print(f"\n== 最终答案 ==\n{ans['final_answer']}", flush=True)
    print(f"\nrelevant_pages: {ans['relevant_pages']}", flush=True)
    print(f"reasoning_summary: {ans['reasoning_summary']}", flush=True)
    print(f"step_by_step_analysis:\n{ans['step_by_step_analysis']}", flush=True)
    print(f"\n# 生成 tokens: 入{gen.tokens_in} / 出{gen.tokens_out}；"
          f"重排 tokens: 入{reranker.tokens_in} / 出{reranker.tokens_out}", flush=True)
    print(f"# 证据块：", flush=True)
    for i, c in enumerate(top[:3], 1):
        print(f"  {i}. llm={c['relevance_score']:.1f} [{c['type']}:p{c['page']}] "
              f"{_snippet(c['text'], 70)}", flush=True)


if __name__ == "__main__":
    main()
